// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSoRet7ptJRkZl_53-kGATG3TREWBl40g',
    appId: '1:198865162295:web:7e731b288fc0a9383d6fb2',
    messagingSenderId: '198865162295',
    projectId: 'silicon-eats-3c79b',
    authDomain: 'silicon-eats-3c79b.firebaseapp.com',
    storageBucket: 'silicon-eats-3c79b.appspot.com',
    measurementId: 'G-CKYPV7H2L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_xTjCjFJDawFRArp44RpT2Fz7dPvUtw',
    appId: '1:198865162295:android:c74a879aff0990f13d6fb2',
    messagingSenderId: '198865162295',
    projectId: 'silicon-eats-3c79b',
    storageBucket: 'silicon-eats-3c79b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANkmYXyxTQ2m5kjuClK0EjI3yWmboIfws',
    appId: '1:198865162295:ios:026be2068805b40e3d6fb2',
    messagingSenderId: '198865162295',
    projectId: 'silicon-eats-3c79b',
    storageBucket: 'silicon-eats-3c79b.appspot.com',
    iosBundleId: 'com.example.sorasummit',
  );
}
